class TiebaEmojis {
  TiebaEmojis._();

  static const Map<String, String> emojiMap = {
    '#(smile)': '🙂',
    '#(laugh)': '😃',
    '#(grin)': '😄',
    '#(joy)': '😂',
    '#(wink)': '😉',
    '#(sunglasses)': '😎',
    '#(heart_eyes)': '😍',
    '#(kissing_heart)': '😘',
    '#(kissing)': '😗',
    '#(stuck_out_tongue_winking_eye)': '😜',
    '#(stuck_out_tongue_closed_eyes)': '😝',
    '#(stuck_out_tongue)': '😛',
    '#(flushed)': '😳',
    '#(grin_sweat)': '😅',
    '#(pensive)': '😔',
    '#(relieved)': '😌',
    '#(unamused)': '😒',
    '#(disappointed)': '😞',
    '#(persevere)': '😣',
    '#(cry)': '😢',
    '#(sob)': '😭',
    '#(sleepy)': '😪',
    '#(sweat)': '😓',
    '#(cold_sweat)': '😰',
    '#(fearful)': '😨',
    '#(scream)': '😱',
    '#(angry)': '😠',
    '#(rage)': '😡',
    '#(triumph)': '😤',
    '#(confounded)': '😖',
    '#(laughing)': '😆',
    '#(mask)': '😷',
    '#(thumbsup)': '👍',
    '#(thumbsdown)': '👎',
    '#(ok_hand)': '👌',
    '#(punch)': '👊',
    '#(fist)': '✊',
    '#(v)': '✌️',
    '#(wave)': '👋',
    '#(hand)': '✋',
    '#(open_hands)': '👐',
    '#(point_up)': '☝️',
    '#(point_down)': '👇',
    '#(point_left)': '👈',
    '#(point_right)': '👉',
    '#(raised_hands)': '🙌',
    '#(pray)': '🙏',
    '#(clap)': '👏',
    '#(muscle)': '💪',
    '#(heart)': '❤️',
    '#(broken_heart)': '💔',
    '#(star)': '⭐',
    '#(fire)': '🔥',
    '#(poop)': '💩',
    '#(rose)': '🌹',
    '#(cake)': '🎂',
    '#(beer)': '🍺',
    '#(coffee)': '☕',
    '#(sun)': '☀️',
    '#(moon)': '🌙',
  };
}
